all:
	python3 visualize.py

clean:
	$(RM) -rf visualize/__pycache__ visualize/parser.out visualize/parsetab.py

test:
	echo "b0-(b-+(b-+(l,l),be+(n)),(cons(c+(be+(n),n),cons(c+(l,n),cons(c+(l,n),n)))))" | python3 visualize.py
